axelera-model-format: 1.0.0

name: facenet-lfw-onnx

description: FaceNet - InceptionResnetV1 with vggface2 weights for face recognition,
  converted from PyTorch to ONNX

pipeline:
  - recognitions:
      model_name: facenet-lfw-onnx
      input:
        type: image
      preprocess:
        - resize:
            height: 192
            width: 192
        - centercrop:
            height: 160
            width: 160
        - torch-totensor:
        - normalize:
            mean: 0.5, 0.5, 0.5
            std: 0.501960784, 0.501960784, 0.501960784
      postprocess:
        - recognition:
            distance_metric: cosine_similarity
            distance_threshold: 0.352
            embeddings_file: embeddings.json
            k: 1
            pair_eval:
              distance_threshold: 0
              k_fold: 10
              plot_roc: true
            update_embeddings: false

models:
  facenet-lfw-onnx:
    class: AxONNXModel
    class_path: $AXELERA_FRAMEWORK/ax_models/base_onnx.py
    weight_path: weights/facenet.onnx
    weight_url: https://media.axelera.ai/artifacts/model_cards/weights/face_recognition/facenet.onnx
    weight_md5: 04028f41a6781c49cb7e98de92e96bc1
    task_category: FaceRecognition
    input_tensor_layout: NCHW
    input_tensor_shape: [1, 3, 160, 160]
    input_color_format: RGB
    num_classes: 3131
    dataset: LFWTorchvisionPair

datasets:
  LFWTorchvisionPair:
    class: TorchvisionPairValidationDataAdapter
    class_path: $AXELERA_FRAMEWORK/ax_datasets/torchvision.py
    dataset_name: LFWPairs
    data_dir_name: LFW
    image_set: deepfunneled
  LFWTorchvisionPeople:
    class: TorchvisionDataAdapter
    class_path: $AXELERA_FRAMEWORK/ax_datasets/torchvision.py
    dataset_name: LFWPeople
    data_dir_name: LFW
    image_set: deepfunneled
