axelera-model-format: 1.0.0

name: facenet-lfw

description: FaceNet - InceptionResnetV1 with vggface2 weights for face recognition

pipeline:
  - recognitions:
      model_name: facenet-lfw
      input:
        type: image
      preprocess:
        - resize:
            height: 192
            width: 192
        - centercrop:
            height: 160
            width: 160
        - torch-totensor:
        - normalize:
            mean: 0.5, 0.5, 0.5
            std: 0.501960784, 0.501960784, 0.501960784
      postprocess:
        - recognition:
            distance_metric: cosine_similarity
            distance_threshold: 0.352
            embeddings_file: embeddings.json
            k: 1
            pair_eval:
              distance_threshold: 0
              k_fold: 10
              plot_roc: true
            update_embeddings: false

models:
  facenet-lfw:
    class: AxFaceNet
    class_path: $AXELERA_FRAMEWORK/ax_models/torch/facenet.py
    weight_path: weights/facenet_vgg_face_2.pt
    weight_url: https://media.axelera.ai/artifacts/model_cards/weights/face_recognition/facenet_vgg_face_2.pt
    weight_md5: 13e767ebf459ce7459f130c3c1398a7b
    task_category: FaceRecognition
    input_tensor_layout: NCHW
    input_tensor_shape: [1, 3, 160, 160]
    input_color_format: RGB
    num_classes: 3131
    dataset: LFWTorchvisionPair

datasets:
  LFWTorchvisionPair:
    class: TorchvisionPairValidationDataAdapter
    class_path: $AXELERA_FRAMEWORK/ax_datasets/torchvision.py
    dataset_name: LFWPairs
    data_dir_name: LFW
    image_set: deepfunneled
  LFWTorchvisionPeople:
    class: TorchvisionDataAdapter
    class_path: $AXELERA_FRAMEWORK/ax_datasets/torchvision.py
    dataset_name: LFWPeople
    data_dir_name: LFW
    image_set: deepfunneled
