axelera-model-format: 1.0.0

name: fastdepth-nyudepthv2-onnx

description: FastDepth with NYU Depth V2 dataset

pipeline:
  - depthestimation:
      model_name: fastdepth-nyudepthv2-onnx
      input:
        type: image
      preprocess:
        - resize:
            width: 224
            height: 224
        - torch-totensor:
      postprocess:
        - image_decoder:
            output_datatype: float32
            scale: False

operators:
  image_decoder:
    class: ImageDecoder
    class_path: $AXELERA_FRAMEWORK/ax_models/decoders/image.py

models:
  fastdepth-nyudepthv2-onnx:
    class: AxONNXModel
    class_path: $AXELERA_FRAMEWORK/ax_models/base_onnx.py
    weight_path: weights/fast_depth_224x224.onnx
    weight_url: https://media.axelera.ai/artifacts/model_cards/weights/depth_estimation/fast_depth_224x224.onnx
    weight_md5: 7280fe93079cfa5fff03c0ac056f6dce
    task_category: DepthEstimation
    input_tensor_layout: NCHW
    input_tensor_shape: [1, 3, 224, 224]
    input_color_format: RGB
    dataset: NYUDepthV2

datasets:
  NYUDepthV2:
    class: DepthEstimationDataAdapter
    class_path: $AXELERA_FRAMEWORK/ax_datasets/depth_estimation.py
    data_dir_name: depthestimation
    val_data: val/official
    cal_data: train_subset
    repr_imgs_dir_path: $AXELERA_FRAMEWORK/data/coco2017_400_b680128
    repr_imgs_url: https://media.axelera.ai/artifacts/data/coco/coco2017_repr400.zip
    repr_imgs_md5: b680128512392586e3c86b670886d9fa
