axelera-model-format: 1.0.0

name: real-esrgan-x4plus-onnx

description: Real-ESRGAN-x4plus super resolution model, converted as ONNX

pipeline:
  - imageenhancement:
      model_name: real-esrgan-x4plus-onnx
      input:
        type: image
      preprocess:
        - resize:
            width: 128
            height: 128
        - torch-totensor:
      postprocess:
        - image_decoder:
            output_datatype: uint8
            scale: True

operators:
  image_decoder:
    class: ImageDecoder
    class_path: $AXELERA_FRAMEWORK/ax_models/decoders/image.py

models:
  real-esrgan-x4plus-onnx:
    class: AxONNXModel
    class_path: $AXELERA_FRAMEWORK/ax_models/base_onnx.py
    weight_path: weights/RealESRGAN_x4plus.onnx
    weight_url: https://media.axelera.ai/artifacts/model_cards/weights/image_enhancement/superresolution/RealESRGAN_x4plus.onnx
    weight_md5: baf06ea5b74bfce40dc2735d9d108741
    task_category: ImageEnhancementSuperResolution
    input_tensor_layout: NCHW
    input_tensor_shape: [1, 3, 128, 128]
    input_color_format: RGB
    dataset: SuperResolutionCustomSet128x128
    extra_kwargs:
      max_compiler_cores: 4
      unlimited_stack_for_compilation: True
      compilation_config:
        resources_used: 1

datasets:
  SuperResolutionCustomSet128x128:
    class: SuperResolutionDataAdapter
    class_path: $AXELERA_FRAMEWORK/ax_datasets/super_resolution.py
    data_dir_name: superres
    val_data: sr_128x128/val
    repr_imgs_dir_path: $AXELERA_FRAMEWORK/data/coco2017_400_b680128
    repr_imgs_url: https://media.axelera.ai/artifacts/data/coco/coco2017_repr400.zip
    repr_imgs_md5: b680128512392586e3c86b670886d9fa
