axelera-model-format: 1.0.0

name: yolov8m-coco-onnx

description: yolov8m ultralytics v8.1.0, 640x640 (COCO), anchor free model
# converted from https://github.com/ultralytics/ultralytics

pipeline:
  - detections:
      model_name: yolov8m-coco-onnx
      input:
        type: image
      preprocess:
        - letterbox:
            width: ${{input_width}}
            height: ${{input_height}}
            scaleup: True
        - torch-totensor:
      postprocess:
        - decodeyolo:
            max_nms_boxes: 30000
            conf_threshold: 0.25
            nms_iou_threshold: 0.45
            nms_class_agnostic: True
            nms_top_k: 300
            eval:
              conf_threshold: 0.001
              nms_iou_threshold: 0.7
              use_multi_label: True
              nms_class_agnostic: False
            box_format: xywh
            normalized_coord: False
            label_filter: ${{label_filter}}
            use_multi_label: False

models:
  yolov8m-coco-onnx:
    class: AxONNXModel
    class_path: $AXELERA_FRAMEWORK/ax_models/base_onnx.py
    weight_path: weights/yolov8m_ultralytics_v8.1.0.onnx
    weight_url: https://media.axelera.ai/artifacts/model_cards/weights/yolo/object_detection/yolov8m_ultralytics_v8.1.0.onnx
    weight_md5: d966c47d3643e98e4f7c1edfe2bf827b
    task_category: ObjectDetection
    input_tensor_layout: NCHW
    input_tensor_shape: [1, 3, 640, 640]
    input_color_format: RGB
    num_classes: 80
    dataset: CocoDataset-COCO2017

datasets: # Python dataloader
  CocoDataset-COCO2017:
    class: ObjDataAdapter
    class_path: $AXELERA_FRAMEWORK/ax_datasets/objdataadapter.py
    data_dir_name: coco
    labels_path: $AXELERA_FRAMEWORK/ax_datasets/labels/coco.names
    label_type: COCO2017
    repr_imgs_dir_path: $AXELERA_FRAMEWORK/data/coco2017_400_b680128
    repr_imgs_url: https://media.axelera.ai/artifacts/data/coco/coco2017_repr400.zip
    repr_imgs_md5: b680128512392586e3c86b670886d9fa

operators:
  decodeyolo:
    class: DecodeYolo
    class_path: $AXELERA_FRAMEWORK/ax_models/decoders/yolo.py
