axelera-model-format: 1.0.0

name: yolov8l-coco

description: yolov8l ultralytics v8.3.0, 640x640 (COCO), anchor free model, native
  PyTorch model

pipeline:
  - detections:
      model_name: yolov8l-coco
      input:
        type: image
      preprocess:
        - letterbox:
            height: ${{input_height}}
            scaleup: true
            width: ${{input_width}}
        - torch-totensor:
      inference:
        handle_all: false
      postprocess:
        - decodeyolo:
            box_format: xywh
            conf_threshold: 0.25
            label_filter: ${{label_filter}}
            max_nms_boxes: 30000
            nms_class_agnostic: true
            nms_iou_threshold: 0.45
            nms_top_k: 300
            normalized_coord: false
            use_multi_label: false
            eval:
              conf_threshold: 0.001
              nms_class_agnostic: false
              nms_iou_threshold: 0.7
              use_multi_label: true

models:
  yolov8l-coco:
    class: AxUltralyticsYOLO
    class_path: $AXELERA_FRAMEWORK/ax_models/yolo/ax_ultralytics.py
    weight_path: weights/yolov8l.pt
    weight_url: https://github.com/ultralytics/assets/releases/download/v8.3.0/yolov8l.pt
    weight_md5: ddeef65794bbf47ddad918fb9c1155fe
    task_category: ObjectDetection
    input_tensor_layout: NCHW
    input_tensor_shape: [1, 3, 640, 640]
    input_color_format: RGB
    num_classes: 80
    dataset: CocoDataset-COCO2017
    extra_kwargs:
      m2:
        mvm_limitation: 57
      compilation_config:
        tiling_depth: 6

datasets:
  CocoDataset-COCO2017:
    class: ObjDataAdapter
    class_path: $AXELERA_FRAMEWORK/ax_datasets/objdataadapter.py
    data_dir_name: coco
    labels_path: $AXELERA_FRAMEWORK/ax_datasets/labels/coco.names
    label_type: COCO2017

model-env:
  dependencies: [ultralytics]

operators:
  decodeyolo:
    class: DecodeYolo
    class_path: $AXELERA_FRAMEWORK/ax_models/decoders/yolo.py
