axelera-model-format: 1.0.0

name: yolox-x-crowdhuman-onnx

description: YOLOX-x trained on CrowdHuman and MOT17 half train set from ByteTrack

pipeline:
  - detections:
      model_name: yolox-x-crowdhuman-onnx
      input:
        type: image
      preprocess:
        - letterbox:
            height: ${{input_height}}
            scaleup: true
            width: ${{input_width}}
        - torch-totensor:
        - normalize:
            mean: [0.485, 0.456, 0.406]
            std: [0.229, 0.224, 0.225]
      inference:
        handle_preamble: true
        handle_transpose: false
        handle_dequantization_and_depadding: false
        handle_postamble: false
      postprocess:
        - decodeyolo:
            box_format: xywh
            conf_threshold: 0.4
            label_filter: ${{label_filter}}
            max_nms_boxes: 30000
            nms_class_agnostic: false
            nms_iou_threshold: 0.6
            nms_top_k: 300
            normalized_coord: false
            use_multi_label: false
            eval:
              conf_threshold: 0.001
              nms_class_agnostic: false
              nms_iou_threshold: 0.65
              use_multi_label: true

models:
  yolox-x-crowdhuman-onnx:
    class: AxONNXModel
    class_path: $AXELERA_FRAMEWORK/ax_models/base_onnx.py
    weight_path: weights/bytetrack_ablation.onnx
    weight_url: https://media.axelera.ai/artifacts/model_cards/weights/yolo/object_detection/bytetrack_ablation.onnx
    weight_md5: be14b5d3927c879fb86f4e4701c3bbd1
    task_category: ObjectDetection
    input_tensor_layout: NCHW
    input_tensor_shape: [1, 3, 800, 1440]
    input_color_format: RGB
    num_classes: 1
    dataset: CocoDataset-COCO2017
    extra_kwargs:
      compilation_config:
        pipeline_channel_tiles: false

datasets:
  CocoDataset-COCO2017:
    class: ObjDataAdapter
    class_path: $AXELERA_FRAMEWORK/ax_datasets/objdataadapter.py
    data_dir_name: CrowdHuman
    ultralytics_data_yaml: data.yaml
    label_type: COCO JSON
    dataset_url: https://media.axelera.ai/artifacts/model_cards/datasets/CrowdHuman_val2.zip
    dataset_md5: 51ecbbc7a0d9fc0279570e6be219b5b1

operators:
  decodeyolo:
    class: DecodeYolo
    class_path: $AXELERA_FRAMEWORK/ax_models/decoders/yolo.py
