axelera-model-format: 1.0.0

name: yolo11n-coco-onnx

description: yolo11n, 640x640 (COCO), anchor free model

pipeline:
  - detections:
      model_name: yolo11n-coco-onnx
      input:
        type: image
      preprocess:
        - letterbox:
            height: ${{input_height}}
            scaleup: true
            width: ${{input_width}}
        - torch-totensor:
      inference:
        handle_all: false
      postprocess:
        - decodeyolo:
            box_format: xywh
            conf_threshold: 0.25
            label_filter: ${{label_filter}}
            max_nms_boxes: 30000
            nms_class_agnostic: true
            nms_iou_threshold: 0.45
            nms_top_k: 300
            normalized_coord: false
            use_multi_label: false
            eval:
              conf_threshold: 0.001
              nms_class_agnostic: false
              nms_iou_threshold: 0.7
              use_multi_label: true

models:
  yolo11n-coco-onnx:
    class: AxONNXModel
    class_path: $AXELERA_FRAMEWORK/ax_models/base_onnx.py
    weight_path: weights/yolo11n-8.3-dynamic.onnx
    weight_url: https://media.axelera.ai/artifacts/model_cards/weights/yolo/object_detection/yolo11n.onnx
    weight_md5: d00108b1a46170499d67a80825531d26
    task_category: ObjectDetection
    input_tensor_layout: NCHW
    input_tensor_shape: [1, 3, 640, 640]
    input_color_format: RGB
    num_classes: 80
    dataset: CocoDataset-COCO2017
    extra_kwargs:
      cal_seed: 129
      num_cal_images: 100
      compilation_config:
        quantization_scheme: per_tensor_min_max
        ignore_weight_buffers: false

datasets:
  CocoDataset-COCO2017:
    class: ObjDataAdapter
    class_path: $AXELERA_FRAMEWORK/ax_datasets/objdataadapter.py
    data_dir_name: coco
    labels_path: $AXELERA_FRAMEWORK/ax_datasets/labels/coco.names
    label_type: COCO2017

operators:
  decodeyolo:
    class: DecodeYolo
    class_path: $AXELERA_FRAMEWORK/ax_models/decoders/yolo.py
