# Ultralytics YOLO Models and Software License
# The Ultralytics YOLO models, along with their supporting files and documentation
# (collectively, the "Software"), are developed and distributed by Ultralytics
# under the GNU Affero General Public License version 3.0 (AGPL-3.0), subject to
# the following modification for Axelera AI:
#
# Evaluation Use Only:
# This Software is solely for testing and evaluation on Axelera AI hardware. Any
# other use requires a commercial license from Ultralytics.
#
# Commercial Use Prohibited Without License:
# Commercial use of this Software, including deployment, reproduction, or
# distribution in products or services internal or external to a commercial
# entity requires an Ultralytics Enterprise License. Visit
# https://www.ultralytics.com/license for licensing details. By using this
# Software, you acknowledge and agree to comply with the above terms.

axelera-model-format: 1.0.0

name: yolov5m-v7-coco

description: YOLOv5m-v7.0, SiLU, 640x640 (COCO)

pipeline:
  - detections:
      model_name: yolov5m-v7-coco
      input:
        type: image
      preprocess:
        - letterbox:
            width: ${{input_width}}
            height: ${{input_height}}
            scaleup: True
        - torch-totensor:
      postprocess:
        - decodeyolo:
            max_nms_boxes: 30000
            conf_threshold: 0.25
            nms_iou_threshold: 0.45
            nms_class_agnostic: False
            nms_top_k: 300
            box_format: xywh
            normalized_coord: False
            label_filter: ${{label_filter}}
            use_multi_label: False
            eval: # overrides for evaluating accuracy
              conf_threshold: 0.001
              nms_iou_threshold: 0.65
              use_multi_label: True
              nms_class_agnostic: False

models:
  yolov5m-v7-coco:
    class: AxYolo
    class_path: $AXELERA_FRAMEWORK/ax_models/yolo/ax_yolo.py
    task_category: ObjectDetection
    input_tensor_layout: NCHW # NCHW / NHWC / CHWN; batch N, channels C, height H, width W
    input_tensor_shape: [1, 3, 640, 640] # corresponding to input format
    input_color_format: RGB # RGB, BGR, Gray
    weight_path: weights/yolov5m-v7.pt
    weight_url: https://media.axelera.ai/artifacts/model_cards/weights/yolo/object_detection/yolov5m.pt
    weight_md5: 76972661b89e5027d6544a4593a7a06b
    num_classes: 80
    dataset: CocoDataset-COCO2017
    extra_kwargs:

datasets: # Python dataloader
  CocoDataset-COCO2017:
    class: ObjDataAdapter
    class_path: $AXELERA_FRAMEWORK/ax_datasets/objdataadapter.py
    data_dir_name: coco
    labels_path: $AXELERA_FRAMEWORK/ax_datasets/labels/coco.names
    # If using a custom dataset, comment out download year and add either
    # repr_imgs or cal_data for calibration and add val_data for validation.
    # You can use your existing training dataset as cal_data
    label_type: COCO2017
    repr_imgs_dir_path: $AXELERA_FRAMEWORK/data/coco2017_400_b680128
    repr_imgs_url: https://media.axelera.ai/artifacts/data/coco/coco2017_repr400.zip
    repr_imgs_md5: b680128512392586e3c86b670886d9fa
    # relative/path/to/your/cal_custom.json or dir with darknet label txt files
    # cal_data: train2017-400.txt
    # val_data: val2017.txt

operators:
  decodeyolo:
    class: DecodeYolo
    class_path: $AXELERA_FRAMEWORK/ax_models/decoders/yolo.py
