axelera-model-format: 1.0.0

name: t5-gst-pipeline

description: Tutorial-5 - An example demonstrating how to deploy an end-to-end GStreamer pipeline to harness the full power of Metis, measuring performance, including FPS and accuracy.

pipeline:
  - classifications:
      model_name: model1
      input:
          type: image
          color_format: RGB
      # here we use built-in preprocess AxOperators to achieve the same effect as your own transforms (override_preprocess)
      preprocess:
        - resize:
            width: 100
            height: 100
        - torch-totensor:
        - normalize:
            mean: 0.485, 0.456, 0.406
            std: 0.229, 0.224, 0.225
      # for general postprocess, we have built-in decoders to help you decode the results without writing any code
      postprocess:
        - topk:
            k: 5

models:
  # ONNX version - if you directly start from this level, you can simply use `AxONNXModel` from `ax_models/base_onnx.py`
  # instead of implementing anything. You can still use your CustomONNXModel from `../onnx/simplest_onnx.py`.
  model1:
    class: AxONNXModel
    class_path: $AXELERA_FRAMEWORK/ax_models/base_onnx.py
    weight_path: ~/.cache/axelera/weights/tutorials/resnet34_fruits360.onnx
  # PyTorch version - if you directly start from this level, you can simply use `CustomPytorchModel` instead of implementing `override_preprocess`. Feel free to replace the following line with `class: CustomPytorchModel` and deploy it.
  # model1:
  #   class: CustomPytorchModel
  #   class_path: ../torch/simplest_torch.py
  #   weight_path: ~/.cache/axelera/weights/tutorials/resnet34_fruits360.pth
    task_category: Classification
    input_tensor_layout: NCHW
    input_tensor_shape: [1, 3, 100, 100]
    input_color_format: RGB
    num_classes: 141
    dataset: Custom-Fruits360

datasets:
  Custom-Fruits360:
    class: CustomDataAdapter
    class_path: tutorial_data_adapter.py
    data_dir_name: fruits-360-100x100
    val_data: Test
    labels_path: ~/.cache/axelera/weights/tutorials/fruits360.names
    repr_imgs_dir_path: $AXELERA_FRAMEWORK/data/fruits-360-100x100/repr_imgs/
