axelera-model-format: 1.0.0

name: t9-cascaded

description: Tutorial-9 - An example demonstrating a cascaded pipeline - A YOLOv8n detector followed by a Resnet34 classifier

pipeline:
  - detections:
      model_name: model1
      preprocess:
        - letterbox:
            width: 640
            height: 640
            scaleup: True
        - torch-totensor:
      postprocess:
        - decodeyolo:
            box_format: xywh
            normalized_coord: False
            max_nms_boxes: 30000
            conf_threshold: 0.25
            nms_iou_threshold: 0.45
            nms_class_agnostic: True
            nms_top_k: 300
            use_multi_label: False
  - classifier:
      model_name: model2
      input:
          type: image
          color_format: RGB
          source: roi
          where: detections
          label_filter: [banana, apple, orange, bowl]
      preprocess:
        - resize:
            width: 100
            height: 100
        - torch-totensor:
        - normalize:
            mean: 0.485, 0.456, 0.406
            std: 0.229, 0.224, 0.225
      postprocess:
        - my_topk_decoder:
        - access_submeta_operator:

operators:
  decodeyolo:
    class: DecodeYolo
    class_path: $AXELERA_FRAMEWORK/ax_models/decoders/yolo.py
  my_topk_decoder:
    class: TopKDecoderCascadedWithMyGstPlugin
    class_path: tutorial_decoders_tu9.py
  access_submeta_operator:
    class: AccessSubMetaOperator
    class_path: tutorial_decoders_tu9.py

models:
  model1:
    class: AxONNXModel
    class_path: $AXELERA_FRAMEWORK/ax_models/base_onnx.py
    weight_path: weights/yolov8n_ultralytics_v8.1.0.onnx
    weight_url: https://media.axelera.ai/artifacts/model_cards/weights/yolo/object_detection/yolov8n_ultralytics_v8.1.0.onnx
    weight_md5: 2ec6c50f5cb0e059344f4ea7f72a3c41
    task_category: ObjectDetection
    input_tensor_layout: NCHW
    input_tensor_shape: [1, 3, 640, 640]
    input_color_format: RGB
    num_classes: 80
    dataset: CocoDataset-COCO2017
    extra_kwargs:
      aipu_cores: 3
  model2:
    class: AxONNXModel
    class_path: $AXELERA_FRAMEWORK/ax_models/base_onnx.py
    weight_path: ~/.cache/axelera/weights/tutorials/resnet34_fruits360.onnx
    task_category: Classification
    input_tensor_layout: NCHW
    input_tensor_shape: [1, 3, 100, 100]
    input_color_format: RGB
    num_classes: 141
    dataset: Custom-Fruits360
    extra_kwargs:
      aipu_cores: 1

datasets:
  CocoDataset-COCO2017:
    class: ObjDataAdapter
    class_path: $AXELERA_FRAMEWORK/ax_datasets/objdataadapter.py
    data_dir_name: coco
    labels_path: $AXELERA_FRAMEWORK/ax_datasets/labels/coco.names
    label_type: COCO2017
  Custom-Fruits360:
    class: CustomDataAdapter
    class_path: tutorial_data_adapter.py
    data_dir_name: fruits-360-100x100
    val_data: Test
    labels_path: ~/.cache/axelera/weights/tutorials/fruits360.names
    repr_imgs_dir_path: $AXELERA_FRAMEWORK/data/fruits-360-100x100/repr_imgs/
