axelera-model-format: 1.0.0

name: osnet-x1-0-msmt17-onnx
description: This is a osnet_x1_0_msmt17_256x128_amsgrad_ep150_stp60_lr0.0015_b64_fb10_softmax_labelsmooth_flip model trained on MSMT17 dataset from https://kaiyangzhou.github.io/deep-person-reid/MODEL_ZOO#imagenet-pretrained-models


pipeline:
  - reid:
      model_name: osnet-x1-0-msmt17-onnx
      input:
          type: image
      preprocess:
        - resize:
            width: 128
            height: 256
        - torch-totensor:
        - normalize:
            mean: [0.485, 0.456, 0.406]
            std: [0.229, 0.224, 0.225]
      postprocess:
        - decodeembeddings:

models:
  osnet-x1-0-msmt17-onnx:
    class: AxONNXModel
    class_path: $AXELERA_FRAMEWORK/ax_models/base_onnx.py
    weight_path: osnet_x1_0_msmt17.onnx
    weight_url: https://media.axelera.ai/artifacts/model_cards/weights/others/re-id/osnet_x1_0_msmt17.onnx
    weight_md5: df0949d82600792dc4ec1d660919dd4f
    task_category: ReIdentification
    input_tensor_layout: NCHW
    input_tensor_shape: [1,3,256,128]
    input_color_format: RGB
    dataset: MSMT17Dataset


datasets:
  MSMT17Dataset:
    class: MSMT17DataAdapter
    class_path: $AXELERA_FRAMEWORK/ax_datasets/reid.py
    data_dir_name: reid
    dump_embeddings_to: embeddings/msmt17-torch.npz
