axelera-model-format: 1.0.0

name: ssd-mobilenetv1-coco-poc-onnx

description: SSD300-MobileNetv1 (COCO) trained from tensorflow1 and converted as ONNX,
  manually edited to PoC. We will fully support it later.

pipeline:
  - detections:
      model_name: ssd-mobilenetv1-coco-poc-onnx
      input:
        type: image
      preprocess:
        - resize:
            half_pixel_centers: true
            height: ${{input_height}}
            width: ${{input_width}}
        - torch-totensor:
            scale: false
        - linear-scaling:
            mean: 127.5
            shift: -1
      inference:
        handle_all: false
      postprocess:
        - decode-ssd-mobilenet:
            box_format: xyxy
            conf_threshold: 0.3
            label_filter: ${{label_filter}}
            max_nms_boxes: 30000
            nms_class_agnostic: true
            nms_iou_threshold: 0.5
            nms_top_k: 200
            normalized_coord: true
            eval:
              conf_threshold: 0.016
              max_nms_boxes: 30000
              nms_class_agnostic: true
              nms_iou_threshold: 0.5
              nms_top_k: 200

models:
  ssd-mobilenetv1-coco-poc-onnx:
    class: AxONNXModel
    class_path: $AXELERA_FRAMEWORK/ax_models/base_onnx.py
    weight_path: weights/ssd300_mobilenet_v1_modified_valid.onnx
    weight_url: https://media.axelera.ai/artifacts/model_cards/weights/object_detection/manual_clean/ssd300_mobilenet_v1_modified_valid.onnx
    weight_md5: a8dc11f8f3f3c92b9775ed9a5d8ca16a
    task_category: ObjectDetection
    input_tensor_layout: NCHW
    input_tensor_shape: [1, 3, 300, 300]
    input_color_format: RGB
    num_classes: 90
    dataset: CocoDataset-COCO2017
    extra_kwargs:
      max_compiler_cores: 4
      compilation_config:
        elf_in_ddr: false

datasets:
  CocoDataset-COCO2017:
    class: ObjDataAdapter
    class_path: $AXELERA_FRAMEWORK/ax_datasets/objdataadapter.py
    data_dir_name: coco
    labels_path: $AXELERA_FRAMEWORK/ax_datasets/labels/coco90.names
    label_type: COCO2017
    format: coco91

operators:
  decode-ssd-mobilenet:
    class: DecodeSsdMobilenet
    class_path: $AXELERA_FRAMEWORK/ax_models/decoders/ssd.py
