axelera-model-format: 1.0.0

name: yolo11nseg-coco-onnx

description: yolo11n seg estimation ultralytics v8.3.0, 640x640 (COCO)

pipeline:
  - segmentations:
      model_name: yolo11nseg-coco-onnx
      input:
        type: image
      preprocess:
        - letterbox:
            half_pixel_centers: true
            height: ${{input_height}}
            scaleup: true
            width: ${{input_width}}
        - torch-totensor:
      inference:
        handle_all: false
      postprocess:
        - decodeyoloseg:
            box_format: xywh
            conf_threshold: 0.25
            label_filter: ${{label_filter}}
            max_nms_boxes: 30000
            nms_class_agnostic: false
            nms_iou_threshold: 0.45
            nms_top_k: 300
            normalized_coord: false
            unpad: true
            use_multi_label: false
            eval:
              conf_threshold: 0.001
              nms_iou_threshold: 0.7
              unpad: false
              use_multi_label: true

models:
  yolo11nseg-coco-onnx:
    class: AxONNXModel
    class_path: $AXELERA_FRAMEWORK/ax_models/base_onnx.py
    weight_path: weights/yolo11n-seg.onnx
    weight_url: https://media.axelera.ai/artifacts/model_cards/weights/yolo/instance_segmentation/yolo11n-seg.onnx
    weight_md5: 572016169506bc288be930070a81d2db
    task_category: InstanceSegmentation
    input_tensor_layout: NCHW
    input_tensor_shape: [1, 3, 640, 640]
    input_color_format: RGB
    num_classes: 80
    dataset: CocoDataset-Segment-COCO2017
    extra_kwargs:
      compilation_config:
        quantization_scheme: per_tensor_min_max
        ignore_weight_buffers: false

datasets:
  CocoDataset-Segment-COCO2017:
    class: SegDataAdapter
    class_path: $AXELERA_FRAMEWORK/ax_datasets/objdataadapter.py
    data_dir_name: coco
    labels_path: $AXELERA_FRAMEWORK/ax_datasets/labels/coco.names
    label_type: COCO2017

operators:
  decodeyoloseg:
    class: DecodeYoloSeg
    class_path: $AXELERA_FRAMEWORK/ax_models/decoders/yoloseg.py
