axelera-model-format: 1.0.0

name: yolo11nseg-coco-onnx

description: yolo11n seg estimation ultralytics v8.3.0, 640x640 (COCO)
# converted from https://github.com/ultralytics/ultralytics

pipeline:
  - segmentations:
      model_name: yolo11nseg-coco-onnx
      input:
        type: image
      preprocess:
        - letterbox:
            width: ${{input_width}}
            height: ${{input_height}}
            scaleup: True
            half_pixel_centers: True
        - torch-totensor:
      postprocess:
        - decodeyoloseg:
            max_nms_boxes: 30000
            conf_threshold: 0.25
            nms_iou_threshold: 0.45
            nms_top_k: 300
            unpad: True
            eval:
              conf_threshold: 0.001
              nms_iou_threshold: 0.7
              use_multi_label: True
              unpad: False
            box_format: xywh
            normalized_coord: False
            label_filter: ${{label_filter}}
            use_multi_label: False
            nms_class_agnostic: False

models:
  yolo11nseg-coco-onnx:
    class: AxONNXModel
    class_path: $AXELERA_FRAMEWORK/ax_models/base_onnx.py
    weight_path: weights/yolo11n-seg.onnx
    weight_url: https://media.axelera.ai/artifacts/model_cards/weights/yolo/instance_segmentation/yolo11n-seg.onnx
    weight_md5: 572016169506bc288be930070a81d2db
    task_category: InstanceSegmentation
    input_tensor_layout: NCHW
    input_tensor_shape: [1, 3, 640, 640]
    input_color_format: RGB
    num_classes: 80
    dataset: CocoDataset-Segment-COCO2017
    extra_kwargs:
      compilation_config:
        quantization_scheme: per_tensor_min_max
        ignore_weight_buffers: False

datasets: # Python dataloader
  CocoDataset-Segment-COCO2017:
    class: SegDataAdapter
    class_path: $AXELERA_FRAMEWORK/ax_datasets/objdataadapter.py
    data_dir_name: coco
    labels_path: $AXELERA_FRAMEWORK/ax_datasets/labels/coco.names
    label_type: COCO2017
    repr_imgs_dir_path: $AXELERA_FRAMEWORK/data/coco2017_400_b680128
    repr_imgs_url: https://media.axelera.ai/artifacts/data/coco/coco2017_repr400.zip
    repr_imgs_md5: b680128512392586e3c86b670886d9fa
    # val_data: val2017.txt
    # mask_size: [160, 160] # 640//4, 640//4

operators:
  decodeyoloseg:
    class: DecodeYoloSeg
    class_path: $AXELERA_FRAMEWORK/ax_models/decoders/yoloseg.py
