axelera-model-format: 1.0.0

name: yolov8sseg-yolov8lpose

description: Cascade example - yolov8sseg cascaded into yolov8lpose

pipeline:
  - segmentations:
      model_name: yolov8sseg-coco-onnx
      template_path: $AXELERA_FRAMEWORK/pipeline-template/yoloseg-letterbox.yaml
      input:
        type: image
      postprocess:
        - decodeyoloseg:
            max_nms_boxes: 30000
            conf_threshold: 0.25
            nms_iou_threshold: 0.45
            nms_top_k: 300
            unpad: True
  - poses:
      model_name: yolov8lpose-coco-onnx
      input:
        type: image
        source: roi
        where: segmentations
        which: CENTER # AREA, SCORE, CENTER
        top_k: 3
      preprocess:
        - letterbox:
            width: 640
            height: 640
            scaleup: True
        - torch-totensor:
      inference:
        handle_all: False
      postprocess:
        - decodeyolopose:
            box_format: xywh # box format of the model output
            normalized_coord: False
            max_nms_boxes: 30000
            conf_threshold: 0.25
            nms_iou_threshold: 0.45
            nms_top_k: 300

operators:
  decodeyolopose:
    class: DecodeYoloPose
    class_path: $AXELERA_FRAMEWORK/ax_models/decoders/yolopose.py
  decodeyoloseg:
    class: DecodeYoloSeg
    class_path: $AXELERA_FRAMEWORK/ax_models/decoders/yoloseg.py

models:
  yolov8lpose-coco-onnx:
    class: AxONNXModel
    class_path: $AXELERA_FRAMEWORK/ax_models/base_onnx.py
    weight_path: weights/yolov8l-pose-v8.1.onnx
    weight_url: https://media.axelera.ai/artifacts/model_cards/weights/yolo/keypoint_detection/yolov8l-pose-v8.1.onnx
    weight_md5: 60955674e106f59a14afcfec5d310f43
    task_category: KeypointDetection
    input_tensor_layout: NCHW
    input_tensor_shape: [1, 3, 640, 640]
    input_color_format: RGB
    num_classes: 1
    dataset: CocoDataset-COCO2017
    extra_kwargs:
      aipu_cores: 2
  yolov8sseg-coco-onnx:
    class: AxONNXModel
    class_path: $AXELERA_FRAMEWORK/ax_models/base_onnx.py
    weight_path: weights/yolov8s-seg-v8.2.onnx
    weight_url: https://media.axelera.ai/artifacts/model_cards/weights/yolo/instance_segmentation/yolov8s-seg-v8.2.onnx
    weight_md5: f773576dba47b14b9ed2b86ea3c3a00f
    task_category: InstanceSegmentation
    input_tensor_layout: NCHW
    input_tensor_shape: [1, 3, 640, 640]
    input_color_format: RGB
    num_classes: 80
    dataset: CocoDataset-COCO2017
    extra_kwargs:
      aipu_cores: 2

datasets:
  CocoDataset-COCO2017:
    class: ObjDataAdapter
    class_path: $AXELERA_FRAMEWORK/ax_datasets/objdataadapter.py
    data_dir_name: coco
    labels_path: $AXELERA_FRAMEWORK/ax_datasets/labels/coco.names
    label_type: COCO2017
