axelera-model-format: 1.0.0

name: yolo11npose-coco-onnx

description: yolo11n pose estimation ultralytics v8.3.0, 640x640 (COCO)
# converted from https://github.com/ultralytics/ultralytics

pipeline:
  - keypoint_detections:
      model_name: yolo11npose-coco-onnx
      input:
        type: image
      preprocess:
        - letterbox:
            width: ${{input_width}}
            height: ${{input_height}}
            scaleup: True
        - torch-totensor:
      postprocess:
        - decodeyolopose:
            max_nms_boxes: 30000
            conf_threshold: 0.25
            nms_iou_threshold: 0.45
            nms_top_k: 300
            eval:
              conf_threshold: 0.001
              nms_iou_threshold: 0.65
            box_format: xywh
            normalized_coord: False

models:
  yolo11npose-coco-onnx:
    class: AxONNXModel
    class_path: $AXELERA_FRAMEWORK/ax_models/base_onnx.py
    weight_path: weights/yolo11n-pose.onnx
    weight_url: https://media.axelera.ai/artifacts/model_cards/weights/yolo/keypoint_detection/yolo11n-pose.onnx
    weight_md5: ffa277388dc15a97330b396ca4565a8a
    task_category: KeypointDetection
    input_tensor_layout: NCHW
    input_tensor_shape: [1, 3, 640, 640]
    input_color_format: RGB
    num_classes: 1
    dataset: CocoDataset-keypoint-COCO2017
    extra_kwargs:
      compilation_config:
        quantization_scheme: per_tensor_min_max
        ignore_weight_buffers: False

datasets: # Python dataloader
  CocoDataset-keypoint-COCO2017:
    class: KptDataAdapter
    class_path: $AXELERA_FRAMEWORK/ax_datasets/objdataadapter.py
    data_dir_name: coco
    label_type: COCO2017
    # TODO: study which representative images are the best
    repr_imgs_dir_path: $AXELERA_FRAMEWORK/data/coco2017_400_b680128
    repr_imgs_url: https://media.axelera.ai/artifacts/data/coco/coco2017_repr400.zip
    repr_imgs_md5: b680128512392586e3c86b670886d9fa
    # without val, will use the default coco2017 val set
    # val_data: dir with yolo label txt files or annotations/person_keypoints_val2017.json
    # if using COCO json format, please specify cal_img_dir / val_img_dir
    # val_img_dir_name: images/val2017

operators:
  decodeyolopose:
    class: DecodeYoloPose
    class_path: $AXELERA_FRAMEWORK/ax_models/decoders/yolopose.py
