axelera-model-format: 1.0.0

name: yolov8lpose-coco

description: yolov8l pose estimation ultralytics v8.1.0, 640x640 (COCO), native PyTorch
  model

pipeline:
  - keypoint_detections:
      model_name: yolov8lpose-coco
      input:
        type: image
      preprocess:
        - letterbox:
            height: ${{input_height}}
            scaleup: true
            width: ${{input_width}}
        - torch-totensor:
      inference:
        handle_all: false
      postprocess:
        - decodeyolopose:
            box_format: xywh
            conf_threshold: 0.25
            max_nms_boxes: 30000
            nms_iou_threshold: 0.45
            nms_top_k: 300
            normalized_coord: false
            eval:
              conf_threshold: 0.001
              nms_iou_threshold: 0.65

models:
  yolov8lpose-coco:
    class: AxUltralyticsYOLO
    class_path: $AXELERA_FRAMEWORK/ax_models/yolo/ax_ultralytics.py
    weight_path: weights/yolov8l-pose.pt
    weight_url: https://github.com/ultralytics/assets/releases/download/v8.3.0/yolov8l-pose.pt
    weight_md5: e441163d8d6f430f2fddf8fa82025e64
    task_category: KeypointDetection
    input_tensor_layout: NCHW
    input_tensor_shape: [1, 3, 640, 640]
    input_color_format: RGB
    num_classes: 1
    dataset: CocoDataset-keypoint-COCO2017
    extra_kwargs:
      m2:
        mvm_limitation: 57

datasets:
  CocoDataset-keypoint-COCO2017:
    class: KptDataAdapter
    class_path: $AXELERA_FRAMEWORK/ax_datasets/objdataadapter.py
    data_dir_name: coco
    label_type: COCO2017

model-env:
  dependencies: [ultralytics]

operators:
  decodeyolopose:
    class: DecodeYoloPose
    class_path: $AXELERA_FRAMEWORK/ax_models/decoders/yolopose.py
