axelera-model-format: 1.0.0

name: ssd-mobilenetv1-coco-tracker

description: Tracker example with SSD300-MobileNetv1 (COCO)

pipeline:
  - detections:
      model_name: SSD-MobileNetV1-COCO
      template_path: $AXELERA_FRAMEWORK/pipeline-template/ssd-tensorflow.yaml
      postprocess:
        - decode-ssd-mobilenet:
            conf_threshold: 0.3
            #label_filter: [bottle, dog] # optional the decoder will only return these labels
  - coco_tracker:
      model_name: tracker
      input:
        source: full
        color_format: RGB
      cv_process:
        - tracker:
            algorithm: oc-sort
            bbox_task_name: detections
            history_length: 30

models:
  SSD-MobileNetV1-COCO:
    class: AxONNXModel
    class_path: $AXELERA_FRAMEWORK/ax_models/base_onnx.py
    weight_path: weights/ssd300_mobilenet_v1_modified_valid.onnx # ssd_mobilenet_v1_coco_2018_01_28.onnx
    weight_url: https://media.axelera.ai/artifacts/weights/ssd/ssd300_mobilenet_v1_modified_valid.onnx
    weight_md5: a8dc11f8f3f3c92b9775ed9a5d8ca16a
    task_category: ObjectDetection
    input_tensor_layout: NCHW
    input_tensor_shape: [1, 3, 300, 300]
    input_color_format: RGB # RGB, BGR, Gray
    num_classes: 90
    dataset: CocoDataset-COCO2017
    extra_kwargs:
      max_compiler_cores: 4
  tracker:
    model_type: CLASSICAL_CV
    task_category: ObjectTracking

datasets:
  CocoDataset-COCO2017:
    class: ObjDataAdapter
    class_path: $AXELERA_FRAMEWORK/ax_datasets/objdataadapter.py
    data_dir_name: coco
    labels_path: $AXELERA_FRAMEWORK/ax_datasets/labels/coco90.names
    # If using a custom dataset, comment out download year and add either
    # repr_imgs or cal_data for calibration and add val_data for validation.
    # You can use your existing training dataset as cal_data
    label_type: COCO2017
    # cal_data: relative/path/to/your/cal_custom.json or dir with darknet label txt files
    # val_data: relative/path/to/your/val_custom.json or dir with darknet label txt files
    format: coco91 # the decoded class follows 0-indexed COCO-91 labels
