axelera-model-format: 1.0.0

name: yolox-oc-sort

description: YOLOX-pedestrian + OC-SORT tracker, bytetrack_m_mot17 model from https://github.com/ifzhang/ByteTrack. To convert the model to onnx, use https://github.com/ifzhang/ByteTrack/tree/main/deploy/ONNXRuntime

pipeline:
  - detections:
      model_name: yolox-pedestrian-onnx
      template_path: $AXELERA_FRAMEWORK/pipeline-template/yolox-letterbox.yaml
      postprocess:
        - decodeyolo:
            max_nms_boxes: 30000
            conf_threshold: 0.6
            nms_iou_threshold: 0.45
            nms_class_agnostic: False
            nms_top_k: 300
            eval:
              conf_threshold: 0.6
      render:
        show_annotations: False
        show_labels: False
  - pedestrian_and_vehicle_tracker:
      model_name: oc_sort
      input:
        source: full
        color_format: RGB
      cv_process:
        - tracker:
            algorithm: oc-sort
            bbox_task_name: detections
            algo_params:
              cmc_enabled: False # Camera Motion Compensation
              det_thresh: 0.6
              min_hits: 3
              iou_threshold: 0.3
              max_id: 0

models:
  yolox-pedestrian-onnx:
    class: AxONNXModel
    class_path: $AXELERA_FRAMEWORK/ax_models/base_onnx.py
    weight_path: weights/bytetrack_m_mot17.onnx
    weight_url: https://d1o2y3tc25j7ge.cloudfront.net/artifacts/model_cards/weights/yolo/object_detection/bytetrack_m_mot17.onnx
    weight_md5: f1c974e53ed65c02b664a228167c3054
    task_category: ObjectDetection
    input_tensor_layout: NCHW
    input_tensor_shape: [1, 3, 800, 1440]
    input_color_format: RGB
    num_classes: 1
    dataset: CocoDataset-COCO2017
  oc_sort:
    model_type: CLASSICAL_CV
    task_category: ObjectTracking
    dataset: TrackerDataset-MOT


datasets:
  CocoDataset-COCO2017:
    class: ObjDataAdapter
    class_path: $AXELERA_FRAMEWORK/ax_datasets/objdataadapter.py
    data_dir_name: coco
    labels_path: $AXELERA_FRAMEWORK/ax_datasets/labels/coco.names
    label_type: COCO2017
  TrackerDataset-MOT:
    class: MotDataAdapter
    class_path: $AXELERA_FRAMEWORK/ax_datasets/mot.py
    data_dir_name: mot
    dataset_name: MOT17 # MOT20, DanceTrack - we support these 3 MOT datasets
    # repr_imgs_dir_name: images/representative
    # repr_imgs_url: https://d1o2y3tc25j7ge.cloudfront.net/artifacts/data/coco/coco2017_repr400.zip
    # repr_imgs_md5: b680128512392586e3c86b670886d9fa
