axelera-model-format: 1.0.0

name: efficientnet_b3-imagenet

description: EfficientNet_B3 (ImageNet) - v1.5 from torchvision

pipeline:
  - classifications:
      model_name: efficientnet_b3-imagenet
      input:
        type: image
      preprocess:
        - resize:
            size: 256
        - centercrop:
            height: ${{input_height}}
            width: ${{input_width}}
        - torch-totensor:
        - normalize:
            mean: 0.485, 0.456, 0.406
            std: 0.229, 0.224, 0.225
      postprocess:
        - topk:
            k: 5

models:
  efficientnet_b3-imagenet:
    class: AxTorchvisionEfficientNet
    class_path: $AXELERA_FRAMEWORK/ax_models/torchvision/efficientnet.py
    task_category: Classification
    input_tensor_layout: NCHW
    input_tensor_shape: [1, 3, 224, 224]
    input_color_format: RGB
    dataset: ImageNet-1K
    num_classes: 1000
    extra_kwargs:
      torchvision_args:
        torchvision_weights_args:
          object: EfficientNet_B3_Weights
          name: IMAGENET1K_V1
      compilation_config:
        enable_icr: false
        quantization_scheme: hybrid_per_tensor_per_channel

datasets:
  ImageNet-1K:
    class: TorchvisionDataAdapter
    class_path: $AXELERA_FRAMEWORK/ax_datasets/torchvision.py
    data_dir_name: ImageNet
    labels_path: $AXELERA_FRAMEWORK/ax_datasets/labels/imagenet1000_clsidx_to_labels.txt
