axelera-model-format: 1.0.0

name: squeezenet1.0-imagenet-onnx

description: squeezenet1.0 (ImageNet) trained from torchvision and converted as ONNX

pipeline:
  - classifications:
      model_name: squeezenet1.0-imagenet-onnx
      input:
        type: image
      preprocess:
        - resize:
            size: 256
        - centercrop:
            height: ${{input_height}}
            width: ${{input_width}}
        - torch-totensor:
        - normalize:
            mean: 0.485, 0.456, 0.406
            std: 0.229, 0.224, 0.225
      postprocess:
        - topk:
            k: 5

models:
  squeezenet1.0-imagenet-onnx:
    class: AxONNXModel
    class_path: $AXELERA_FRAMEWORK/ax_models/base_onnx.py
    weight_path: weights/squeezenet1_0_pretrained.onnx
    weight_url: https://media.axelera.ai/artifacts/model_cards/weights/classification/squeezenet1_0_pretrained.onnx
    weight_md5: 9dab4b113a3dd410e4b5234f73da7221
    task_category: Classification
    input_tensor_layout: NCHW
    input_tensor_shape: [1, 3, 224, 224]
    input_color_format: RGB
    dataset: ImageNet-1K
    num_classes: 1000
    extra_kwargs:
      max_compiler_cores: 4

datasets:
  ImageNet-1K:
    class: TorchvisionDataAdapter
    class_path: $AXELERA_FRAMEWORK/ax_datasets/torchvision.py
    data_dir_name: ImageNet
    labels_path: $AXELERA_FRAMEWORK/ax_datasets/labels/imagenet1000_clsidx_to_labels.txt
