axelera-model-format: 1.0.0

name: wide_resnet50-imagenet

description: Wide ResNet-50 (ImageNet) - v1.5 from torchvision

pipeline:
  - classifications:
      model_name: wide_resnet50-imagenet
      input:
        type: image
      preprocess:
        - resize:
            size: 256
        - centercrop:
            height: ${{input_height}}
            width: ${{input_width}}
        - torch-totensor:
        - normalize:
            mean: 0.485, 0.456, 0.406
            std: 0.229, 0.224, 0.225
      postprocess:
        - topk:
            k: 5

models:
  wide_resnet50-imagenet:
    class: AxTorchvisionResNet
    class_path: $AXELERA_FRAMEWORK/ax_models/torchvision/resnet.py
    task_category: Classification
    input_tensor_layout: NCHW
    input_tensor_shape: [1, 3, 224, 224]
    input_color_format: RGB
    dataset: ImageNet-1K
    num_classes: 1000
    extra_kwargs:
      torchvision_args:
        block: Bottleneck
        layers: [3, 4, 6, 3]
        width_per_group: 128
        torchvision_weights_args:
          object: Wide_ResNet50_2_Weights
          name: IMAGENET1K_V1

datasets:
  ImageNet-1K:
    class: TorchvisionDataAdapter
    class_path: $AXELERA_FRAMEWORK/ax_datasets/torchvision.py
    data_dir_name: ImageNet
    labels_path: $AXELERA_FRAMEWORK/ax_datasets/labels/imagenet1000_clsidx_to_labels.txt
